name: Discord Notifications

on:
  workflow_run:
    workflows: ["PR Checks"]
    types:
      - completed

jobs:
  discord-notification:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'failure'
    steps:
      - name: Get PR details
        id: pr-details
        uses: actions/github-script@v7
        with:
          script: |
            const { data: pullRequests } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: `${context.repo.owner}:${context.payload.workflow_run.head_branch}`,
              state: 'open'
            });
            
            if (pullRequests.length > 0) {
              const pr = pullRequests[0];
              core.setOutput('pr_number', pr.number);
              core.setOutput('pr_title', pr.title);
              core.setOutput('pr_author', pr.user.login);
              core.setOutput('pr_url', pr.html_url);
              core.setOutput('branch', pr.head.ref);
            }

      - name: Send Discord notification on failure
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: failure
          title: "PR Checks Failed"
          description: |
            **Pull Request:** #${{ steps.pr-details.outputs.pr_number }} - ${{ steps.pr-details.outputs.pr_title }}
            **Author:** ${{ steps.pr-details.outputs.pr_author }}
            **Branch:** ${{ steps.pr-details.outputs.branch }}
            
            **Workflow:** ${{ github.event.workflow_run.name }}
            **Run ID:** ${{ github.event.workflow_run.id }}
            
            One or more checks failed in the PR validation pipeline.
            
            [View Pull Request](${{ steps.pr-details.outputs.pr_url }})
            [View Failed Run](${{ github.event.workflow_run.html_url }})
          color: 0xff0000
          username: "GitHub Actions Bot"
          avatar_url: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"