name: Monorepo PR Checks

on:
  pull_request:
    branches: [main]

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      devmet-app: ${{ steps.filter.outputs.devmet-app }}
      devmet-ui: ${{ steps.filter.outputs.devmet-ui }}
      devmet-backend: ${{ steps.filter.outputs.devmet-backend }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            devmet-app:
              - 'apps/devmet-app/**'
              - 'pnpm-workspace.yaml'
              - 'package.json'
              - 'pnpm-lock.yaml'
            devmet-ui:
              - 'package/devmet-ui/**'
              - 'pnpm-workspace.yaml'
              - 'package.json'
              - 'pnpm-lock.yaml'
            devmet-backend:
              - 'apps/devmet-backend/**'
              - 'pnpm-workspace.yaml'
              - 'package.json'
              - 'pnpm-lock.yaml'

  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v4
        with:
          version: 8.15.6
          
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

  devmet-app:
    needs: [detect-changes, setup]
    if: needs.detect-changes.outputs.devmet-app == 'true' && github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run lint
        run: pnpm --filter devmet-app run lint

      - name: Run typecheck
        run: pnpm --filter devmet-app run typecheck

      - name: Run build
        run: pnpm --filter devmet-app run build

  devmet-ui:
    needs: [detect-changes, setup]
    if: needs.detect-changes.outputs.devmet-ui == 'true' && github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run lint
        run: pnpm --filter devmet-ui run lint

      - name: Run build
        run: pnpm --filter devmet-ui run build

  devmet-backend:
    needs: [detect-changes, setup]
    if: needs.detect-changes.outputs.devmet-backend == 'true' && github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run lint
        run: pnpm --filter devmet-backend run lint

      - name: Run build
        run: pnpm --filter devmet-backend run build

  summary:
    runs-on: ubuntu-latest
    needs: [devmet-app, devmet-ui, devmet-backend]
    if: always()
    steps:
      - name: Show status
        run: |
          echo "devmet-app: ${{ needs.devmet-app.result }}"
          echo "devmet-ui: ${{ needs.devmet-ui.result }}"
          echo "devmet-backend: ${{ needs.devmet-backend.result }}"
          if [[ "${{ needs.devmet-app.result }}" == "failure" ]]; then exit 1; fi
          if [[ "${{ needs.devmet-ui.result }}" == "failure" ]]; then exit 1; fi
          if [[ "${{ needs.devmet-backend.result }}" == "failure" ]]; then exit 1; fi