name: PR Checks

on:
  pull_request:
    branches: [main]

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      devmet-app: ${{ steps.filter.outputs.devmet-app }}
      devmet-ui: ${{ steps.filter.outputs.devmet-ui }}
      devmet-backend: ${{ steps.filter.outputs.devmet-backend }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          submodules: recursive
          fetch-depth: 0

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            devmet-app:
              - 'apps/devmet-apps/**'
              - 'pnpm-workspace.yaml'
              - 'package.json'
            devmet-ui:
              - 'package/devmet-ui/**'
              - 'pnpm-workspace.yaml'
              - 'package.json'
            devmet-backend:
              - 'apps/devmet-backend/**'
              - 'pnpm-workspace.yaml'
              - 'package.json'

  devmet-app:
    needs: changes
    if: needs.changes.outputs.devmet-app == 'true' && github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 8.15.6

      - name: Install dependencies
        working-directory: ${{ github.workspace }}
        run: pnpm install

      - name: Lint
        working-directory: ${{ github.workspace }}
        run: pnpm --filter devmet-app lint

      - name: Typecheck
        working-directory: ${{ github.workspace }}
        run: pnpm --filter devmet-app typecheck

      - name: Build
        working-directory: ${{ github.workspace }}
        run: pnpm --filter devmet-app build

  devmet-ui:
    needs: changes
    if: needs.changes.outputs.devmet-ui == 'true' && github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 8.15.6

      - name: Install dependencies
        working-directory: ${{ github.workspace }}
        run: pnpm install

      - name: Lint
        working-directory: ${{ github.workspace }}
        run: pnpm --filter devmet-ui lint

      - name: Build
        working-directory: ${{ github.workspace }}
        run: pnpm --filter devmet-ui build

  devmet-backend:
    needs: changes
    if: needs.changes.outputs.devmet-backend == 'true' && github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 8.15.6

      - name: Install dependencies
        working-directory: ${{ github.workspace }}
        run: pnpm install

      - name: Lint
        working-directory: ${{ github.workspace }}
        run: pnpm --filter devmet-backend lint

      - name: Build
        working-directory: ${{ github.workspace }}
        run: pnpm --filter devmet-backend build

  pr-checks-complete:
    runs-on: ubuntu-latest
    needs: [changes, devmet-app, devmet-ui, devmet-backend]
    if: always()
    steps:
      - name: Check all jobs status
        run: |
          echo "Changes: ${{ needs.changes.result }}"
          echo "devmet-app: ${{ needs.devmet-app.result }}"
          echo "devmet-ui: ${{ needs.devmet-ui.result }}"
          echo "devmet-backend: ${{ needs.devmet-backend.result }}"
          
          if [[ "${{ needs.changes.result }}" == "failure" ]]; then
            echo "Changes job failed"
            exit 1
          fi
          if [[ "${{ needs.devmet-app.result }}" == "failure" ]]; then
            echo "devmet-app job failed"
            exit 1
          fi
          if [[ "${{ needs.devmet-ui.result }}" == "failure" ]]; then
            echo "devmet-ui job failed"
            exit 1
          fi
          if [[ "${{ needs.devmet-backend.result }}" == "failure" ]]; then
            echo "devmet-backend job failed"
            exit 1
          fi

          echo "All jobs completed successfully!"
