# .github/workflows/pr-checks.yml
name: PR-checks
on:
  pull_request:
    branches: [main]

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      backend: ${{ steps.filter.outputs.backend }}
      ui: ${{ steps.filter.outputs.ui }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            frontend:
              - 'apps/devmet-app/**'
            backend:
              - 'apps/devmet-backend/**'
            ui:
              - 'packages/devmet-ui/**'

  lint-and-typecheck:
    needs: detect-changes
    runs-on: ubuntu-latest
    if: |
      needs.detect-changes.outputs.frontend == 'true' ||
      needs.detect-changes.outputs.backend == 'true' ||
      needs.detect-changes.outputs.ui == 'true'
    strategy:
      matrix:
        target: [frontend, backend, ui]
        include:
          - target: frontend
            path: apps/devmet-app
          - target: backend
            path: apps/devmet-backend
          - target: ui
            path: packages/devmet-ui
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Build project
        working-directory: ${{ matrix.path }}
        run: pnpm build
      
      - name: Run lint and typecheck for ${{ matrix.target }}
        if: needs.detect-changes.outputs[matrix.target] == 'true'
        working-directory: ${{ matrix.path }}
        run: |
          pnpm lint
          pnpm typecheck

  test:
    needs: detect-changes
    runs-on: ubuntu-latest
    if: |
      needs.detect-changes.outputs.frontend == 'true' ||
      needs.detect-changes.outputs.backend == 'true' ||
      needs.detect-changes.outputs.ui == 'true'
    strategy:
      matrix:
        target: [frontend, backend, ui]
        include:
          - target: frontend
            path: apps/devmet-app
          - target: backend
            path: apps/devmet-backend
          - target: ui
            path: packages/devmet-ui
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install
      
      # - name: Run tests for ${{ matrix.target }}
      #   if: needs.detect-changes.outputs[matrix.target] == 'true'
      #   working-directory: ${{ matrix.path }}
      #   # run: pnpm test

  # Summary job to check if all required checks passed
  pr-checks-complete:
    needs: [detect-changes, lint-and-typecheck, test]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Check if all jobs succeeded or were skipped
        run: |
          if [[ "${{ needs.lint-and-typecheck.result }}" =~ ^(success|skipped)$ && "${{ needs.test.result }}" =~ ^(success|skipped)$ ]]; then
            echo "All PR checks passed!"
            exit 0
          else
            echo "Some PR checks failed!"
            exit 1
            fi
