name: Monorepo PR Checks

on:
  pull_request:
    branches: [main]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      devmet-app: ${{ steps.filter.outputs.devmet-app }}
      devmet-ui: ${{ steps.filter.outputs.devmet-ui }}
      devmet-backend: ${{ steps.filter.outputs.devmet-backend }}
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          submodules: recursive
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.15.6

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install root dependencies
        run: pnpm install

      - name: Detect changed paths
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            devmet-app:
              - 'apps/devmet-apps/**'
              - 'pnpm-workspace.yaml'
              - 'package.json'
              - 'pnpm-lock.yaml'
            devmet-ui:
              - 'package/devmet-ui/**'
              - 'pnpm-workspace.yaml'
              - 'package.json'
              - 'pnpm-lock.yaml'
            devmet-backend:
              - 'apps/devmet-backend/**'
              - 'pnpm-workspace.yaml'
              - 'package.json'
              - 'pnpm-lock.yaml'

  devmet-app:
    needs: setup
    if: needs.setup.outputs.devmet-app == 'true' && github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          submodules: recursive
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 8.15.6

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          cd apps/devmet-apps
          pnpm install

      - name: Lint
        run: |
          cd apps/devmet-apps
          pnpm run lint

      - name: Typecheck
        run: |
          cd apps/devmet-apps
          pnpm run typecheck

      - name: Build
        run: |
          cd apps/devmet-apps
          pnpm run build

  devmet-ui:
    needs: setup
    if: needs.setup.outputs.devmet-ui == 'true' && github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          submodules: recursive
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 8.15.6

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          cd package/devmet-ui
          pnpm install

      - name: Lint
        run: |
          cd package/devmet-ui
          pnpm run lint

      - name: Build
        run: |
          cd package/devmet-ui
          pnpm run build

  devmet-backend:
    needs: setup
    if: needs.setup.outputs.devmet-backend == 'true' && github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          submodules: recursive
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 8.15.6

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          cd apps/devmet-backend
          pnpm install

      - name: Lint
        run: |
          cd apps/devmet-backend
          pnpm run lint

      - name: Build
        run: |
          cd apps/devmet-backend
          pnpm run build

  pr-checks-complete:
    runs-on: ubuntu-latest
    needs: [setup, devmet-app, devmet-ui, devmet-backend]
    if: always()
    steps:
      - name: Check job statuses
        run: |
          echo "Job Status Report:"
          echo "------------------"
          echo "devmet-app: ${{ needs.devmet-app.result }}"
          echo "devmet-ui: ${{ needs.devmet-ui.result }}"
          echo "devmet-backend: ${{ needs.devmet-backend.result }}"
          
          if [[ "${{ needs.setup.result }}" == "failure" ]]; then
            echo "::error::Setup job failed"
            exit 1
          fi
          
          if [[ "${{ needs.devmet-app.result }}" == "failure" ]]; then
            echo "::error::devmet-app checks failed"
            exit 1
          fi
          
          if [[ "${{ needs.devmet-ui.result }}" == "failure" ]]; then
            echo "::error::devmet-ui checks failed"
            exit 1
          fi
          
          if [[ "${{ needs.devmet-backend.result }}" == "failure" ]]; then
            echo "::error::devmet-backend checks failed"
            exit 1
          fi

          echo "✅ All checks passed successfully!"
